version: "3.8"

services:
  node:
    container_name: debian_node
    build: .
    ports:
      - 3000:3000
    networks:
      - labiak
    volumes:
      - .:/server
      - node_modules:/node_modules
    environment:
      HOST: '0.0.0.0'
      PORT: 3000
    command: ./start.sh

networks:
  labiak:
    driver: bridge

volumes:
  node_modules:
